name: Deploy frontend to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  configuration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run deploy script
        run: sh deploy.sh

      - name: Upload configured workspace
        uses: actions/upload-artifact@v4
        with:
          name: configured-workspace
          path: .
          include-hidden-files: true
          if-no-files-found: error

  deploy-tmc-ui:
    needs: configuration
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download configured workspace
        uses: actions/download-artifact@v4
        with:
          name: configured-workspace
          path: .
      

      - name: Set config - base path
        run: |
          sed -i "s|return {|return {\n    base: '/${{ github.event.repository.name }}/',|" vite.config.mjs
          echo "=== vite.config.mjs after modification ==="
          cat vite.config.mjs
      - name: Set config - catalog URL
        run: |
          CATALOG_URL="${{ github.repository }}"
          echo "Setting __CATALOG_URL__ to: $CATALOG_URL"
          sed -i -E "s|__CATALOG_URL__:[[:space:]]*JSON.stringify(.*)|__CATALOG_URL__: JSON.stringify(\"$CATALOG_URL\"),|g" vite.config.mjs
          echo "=== vite.config.mjs after __CATALOG_URL__ update ==="
          cat vite.config.mjs
                
      - name: Set tool - yarn
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
